name: Publish package to GitHub Packages
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: sqa-artifactory
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.SQA_ARTIFACTORY_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SQA_ARTIFACTORY_TOKEN }}